### ISSUE TITLE
Works great

### ISSUE THREAD

**Issue by Retch** [cicirello/javadoc-cleanup#6]
It is working very good, but it would be interesting to see whether the "splitindex" [javadoc parameter](http://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#splitindex) would work, i couldn't get it running with the parameter.

**Comment by cicirello** [comment]
@Retch What happens when the splitindex javadoc is used?

**Comment by Retch** [comment]
When splitindex is passed in as argument, the index page is a bit lighter because only the classes with the selected letter are shown, and not all classes from A-Z.
I didn't get it working to pass in the argument, thats the prob.

**Comment by cicirello** [comment]
@Retch Do you mean you're having trouble getting javadoc to recognize that option?  If you are using mvn, then in your pom.xml, where you have the `maven-javadoc-plugin` configured, somewhere between the `<configuration>` and `</configuration>`, add `<splitindex>true</splitindex>`.  But don't put it inside of additionalJOptions.

**Comment by Retch** [comment]
Thanks, but i don't have the javadoc plugin in the pom.xml
You could see [here](https://github.com/fh-erfurt/Scooter-MS) for youself, but this is just a little thing and nothing real important.

**Comment by cicirello** [comment]
You're welcome.
